#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#         * compound commands having a testable exit status, especially «case»;
#         * various built-in commands including «command», «set», and «ulimit».
#
#   Important for patching:
#
#   (2) This script targets any POSIX shell, so it avoids extensions provided
#       by Bash, Ksh, etc; in particular arrays are avoided.
#
#       The "traditional" practice of packing multiple parameters into a
#       space-separated string is a well documented source of bugs and security
#       problems, so this is (mostly) avoided, by progressively accumulating
#       options in "$@", and eventually passing that to Java.
#
#       Where the inherited environment variables (DEFAULT_JVM_OPTS, JAVA_OPTS,
#       and GRADLE_OPTS) rely on word-splitting, this is performed explicitly;
#       see the in-line comments for details.
#
#       There are tweaks for specific operating systems such as AIX, CygWin,
#       Darwin, MinGW, and NonStop.
#
#   (3) This script is generated from the Groovy template
#       https://github.com/gradle/gradle/blob/HEAD/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
#       within the Gradle project.
#
#       You can find Gradle at https://github.com/gradle/gradle/.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order to eventually pass to java.
# We cannot use arrays for this, because relying on them causes "fork bomb" behavior on some POSIX systems.
# So we stack arguments in $ARGV counteractively, building a command line that proceeds using that slow style.

# To make this script Mac OSX friendly, we skip the "cp" parsing of the arguments.

# Split the _JAVA_OPTIONS and JAVA_OPTS and GRADLE_OPTS values into separate arguments
# This simulates the word splitting that bash and ksh provide, allowing the script to integrate with the
# IDEA JWT script's "jr" and "idea" scripts, which rely on word splitting to pass arguments to gradle.
# In particular:
#   The grammar uses: OptionCanonicalizer = '$JAVA_OPTS' || '$GRADLE_OPTS' || ... ;
#   This enables: export GRADLE_OPTS='"$GRADLE_OPTS" \"-Pproperty=value\"'
#   This behaves like: GRADLE_OPTS = (general jvm args) (space) (property) (space) (property) etc.
#
# We don't use word splitting on environment variables because that can cause unstable behavior.
# So we use "set +f" to disable glob matching, then iterate over the environment variable's value expanding the tokens.
# This is necessary because the ~1..* character ' ' is a separator for splitting.

# Save the original arguments
ORIGINAL_ARGVs=$*

# Pre-collect any GRADLE_OPTS or JAVA_OPTS that might contain quoted arguments.
# Use set +f to disable globbing so that we can split on spaces without worrying about expansion.
set +f

# Split GRADLE_OPTS
if [ -n "$GRADLE_OPTS" ]; then
    # Use eval to simulate shell word splitting, as if the $GRADLE_OPTS were parsed as shell arguments.
    # This will preserve quoted arguments like: -Dfoo="bar baz"
    eval GRADLE_OPTS_TO_SPLIT=\"$GRADLE_OPTS\"
    # We don't need to keep GRADLE_OPTS around, so we can set it to the split version.
    set -- $GRADLE_OPTS_TO_SPLIT
    unset GRADLE_OPTS_TO_SPLIT
    # Append the split GRADLE_OPTS to the current arguments.
    for arg do
        ARGV[${#ARGV[@]}]=$arg
    done
fi

# Split JAVA_OPTS
if [ -n "$JAVA_OPTS" ]; then
    eval JAVA_OPTS_TO_SPLIT=\"$JAVA_OPTS\"
    set -- $JAVA_OPTS_TO_SPLIT
    unset JAVA_OPTS_TO_SPLIT
    for arg do
        ARGV[${#ARGV[@]}]=$arg
    done
fi

# Split _JAVA_OPTIONS
if [ -n "$_JAVA_OPTIONS" ]; then
    eval _JAVA_OPTIONS_TO_SPLIT=\"$_JAVA_OPTIONS\"
    set -- $_JAVA_OPTIONS_TO_SPLIT
    unset _JAVA_OPTIONS_TO_SPLIT
    for arg do
        ARGV[${#ARGV[@]}]=$arg
    done
fi

# Restore the default behavior
set -f

# Collect all arguments in reverse stack order (so that ARGV is a valid arguments list after the loop).
ARGV=()
while [ $# -gt 0 ]; do

    # Remove the argument from the command line
    arg=$1
    shift

    # Check if the argument is an option whose argument(s) are attached with =, :, etc.
    case $arg in
        # Short options, possibly with argument attached
        -[dDm]?*)
            # Short option with argument attached: split it up.
            # key="${arg:2}" # Not needed for now, as we pass the whole arg to java.
            # In POSIX sh, substring is not available. So we just pass the whole arg to java.
            # Eventually, we should split the arg into option and argument.
            ARGV[${#ARGV[@]}]=$arg
            ;;
        # Long options with arguments, or options that just need to be passed through
        *)
            ARGV[${#ARGV[@]}]=$arg
            ;;
    esac
done

# Prepend DEFAULT_JVM_OPTS and any remaining command line arguments to the final command.
# Use the whole ARGV as the command line, but we need to prepend DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS.
# We do this by building the command in a loop.

# The command line we'll execute is:
#   java $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS -cp $CLASSPATH org.gradle.wrapper.GradleWrapperMain "$@"
# We need to quote the classpath and the main class for when there are spaces in the path.
# We also need to ensure the arguments for the main class are properly quoted.

# Build the argument list in reverse order.
# We will prepend the main class and the classpath after building the rest of the arguments.
REV_ARGS=()
for arg in "${ARGV[@]}"; do
    REV_ARGS=("$arg" "${REV_ARGS[@]}")
done

# Prepend the main class and classpath to the reverse arguments.
REV_ARGS=( "-cp" "$CLASSPATH" "org.gradle.wrapper.GradleWrapperMain" "${REV_ARGS[@]}" )

# Prepend the JVM options.
REV_ARGS=( $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "${REV_ARGS[@]}" )

# Now execute the java command.
exec "$JAVACMD" "${REV_ARGS[@]}"
